site_name: Admonitions
repo_url: https://github.com/PGijsbers/admonitions
theme:  material

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - "gh-admonitions"