[project]
name="gtm-admonitions"
version="0.0.1"
dependencies=[
  "mkdocs",
]

[project.optional-dependencies]
docs=[
  "mkdocs-material",
]
dev=[
  "pytest",
]

[project.entry-points."mkdocs.plugins"]
gtmm-admonitions = "gtmm_admonitions.admonition:AdmonitionConverter"
