[project]
name="mkdocs-github-admonitions-plugin"
version="0.0.1"
dependencies=[
  "mkdocs",
]

[project.optional-dependencies]
docs=[
  "mkdocs-material",
]
dev=[
  "pytest",
]

[project.entry-points."mkdocs.plugins"]
gh-admonitions = "src.admonition:AdmonitionConverter"
